### ISSUE TITLE
Improve proxy security

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#100]
We have HTTP proxy in `proxy/` folder to bypass CORS limits in the browser.

But I’m afraid that spammer could use it. Unfortunately, we can’t use authentication since we care about privacy.

- [x] Let’s allow only `GET` request for now, since `POST`/`PUT` is methods to change documents, and we don’t need them to load RSS.
- [x] Remove all cookie headers. Otherwise, our proxy will copy headers and set cookie for own domain. For instance, `cookie` from client and `set-cookie` from server.
- [x] In `process.env.NODE_ENV === 'production'` allow requests only from `*.slowreader.app` clients using `Origin` header.
- [x] Do not allow request to localhost IP addressed like `127.*` or `192.168.*` (check all possible local IP addresses), since it can be used to access to cloud infrastructure.
- [x] Remove `Host` header from client since it will be the proxy domain.
- [x] Add unit tests to proxy like we have in the core.

**Comment by nbbrdn** [comment]
I want to take it

**Comment by toplenboren** [comment]
Hey, can I take this? I like security features :-)

**Comment by toplenboren** [comment]
I want to take it

**Comment by ai** [comment]
Sure. The task is on you.

**Comment by toplenboren** [comment]
Hi, still on it

**Comment by ai** [comment]
@toplenboren create a draft PR if so 😸

**Comment by toplenboren** [comment]
Hi! Have some questions before moving further.

- There are a [plethora of reserved addresses](https://en.wikipedia.org/wiki/Reserved_IP_addresses) for both `ipv4` and `ipv6` I think we should ban requests for them. wdyt?

- I think we should also ban all protocols besides `http` / `https`  and `rss`, so that `<proxy>/ssh:hehe.com` would not work. Wdyt?

- Do you think we should implement some kind of rate limiter here? I think maybe we can ban for 1 minute (return 500) by ip if user tries to do more then 4 requests in second

**Comment by toplenboren** [comment]
> I think it is nice idea, but not to ban, but postpone. 4 requests in a minute is pretty normal for RSS search on website. But we can add 50 to prevent using us as DDoS proxy.

Really liked your Idea to add debounce here.. Will see what I can do! Thanks for guidance :-)
