### ISSUE TITLE
Fix `<Select>` in Safari

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#121]
Seems like we have a problem with select. In Firefox it shows drop-down list on click, but in Safari no.

https://github.com/hplush/slowreader/assets/19343/9c5c75fb-8175-423a-a441-e7e8cb66ee15

**Comment by Konfuze** [comment]
Found out that problem is in the default `appearance` of `select` in Safari, it's height not changes even if we set `height: 1000px`

If we reset appearance by setting `appearance: none`, it affects the font:
<img width="227" alt="Screenshot 2024-03-27 at 17 46 39" src="https://github.com/hplush/slowreader/assets/131331/c3f3706a-6a8a-47a6-8ae0-15bdbb50c8d0">

So we need to add `font: revert` to make it default:
<img width="175" alt="Screenshot 2024-03-27 at 17 48 06" src="https://github.com/hplush/slowreader/assets/131331/97ce4f96-4dd8-4849-b172-bb56256ddf2d">

I'll make fix for that

**Comment by ai** [comment]
Great, thanks!
