### ISSUE TITLE
Add `theme-color`

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#75]
We need a user with Chrome for Android to add this feature and test it.

- [ ] Add `theme-color` meta tag for light and dark color. We can use `--land-color` for that.
- [ ] Change them on switching to reading mode.
- [ ] Try to find a way to get colors in JS from CSS (maybe create separated CSS Custom Properties for background colors).

**Comment by privorotskii** [comment]
I want to take it

**Comment by privorotskii** [comment]
Hey @ai, I did some context gathering on that, can we discuss it a bit?

Do I get it right that the ultimate goal is to get the Safari's top bar color aligned to the theme color?

Here's a bit of context:

- As far as I see the meta tag is [handled by Safari, Chrome for Android and Samsung internet](https://caniuse.com/meta-theme-color)
  - Chrome for Desktop uses this tag only on PWA
- Safari on desktop uses this tag in compact mode which is set in settings, otherwise it's ignored
- Safari doesn't take into account the value of theme-color meta tag if it's set via `var()`
- Safari makes the top bar color aligned to the background by default itself
- In the reading mode it uses background color neither for page nor for the top bar

So to summarize: if the ultimate goal is to have the top bar color the same as the background, it's applied by Safari itself by default. 

However, we may still want to add this tag for the sake of making it explicit and to add it for Chrome Android and Samsung Internet, but at the moment I don't see a good way to do it without hardcoding the colours.
`--land-color` is a CSS custom property, so it should be something like this

```html
  <meta name="theme-color" content="var(--land-color)" />
```

But the `var` as a value is ignored by Safari, so it won't be applied

Safari Compact mode:
| Light mode | Dark mode |
|--------|--------|
| ![Image](https://github.com/hplush/slowreader/assets/10295457/b26692ac-db59-43b0-b356-8e129a8491aa)| ![Image](https://github.com/hplush/slowreader/assets/10295457/d3217c7b-2943-4e9d-b5b8-ba80ca35aed6) |

Safari separate mode:
| Light mode | Dark mode |
|--------|--------|
| ![Image](https://github.com/hplush/slowreader/assets/10295457/c410b3bd-9bb2-4163-a9fa-2fda6ebd5f4a)| ![Image](https://github.com/hplush/slowreader/assets/10295457/dd0f74d6-b711-4e49-8d83-26a08e602c77) |

Safari in reading mode:
| Light mode | Dark mode |
|--------|--------|
| ![Image](https://github.com/hplush/slowreader/assets/10295457/32e9357b-8f7e-4b2a-b249-3b0ccab14ea9)| ![Image]![Image](https://github.com/hplush/slowreader/assets/10295457/26f47835-73a8-45ea-b466-b622b99a31d0) |

- `question` Are we okay with adding tags with hardcoded colours for Chrome for Android and Samsung Internet?

Something like this
```html
<meta name="theme-color" media="(prefers-color-scheme: light)" content="light-value-here" />
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="dark-value-here" />
```

**Comment by ai** [comment]
> Do I get it right that the ultimate goal is to get the Safari's top bar color aligned to the theme color?

Yes

> So to summarize: if the ultimate goal is to have the top bar color the same as the background, it's applied by Safari itself by default.

OK. Let’s add it only for Chrome for Android (still a big use base). But even Chrome for Android use `theme-color` not every time but only in light theme (we may still want to support dark theme for the future).

Do you have Android and Chrome (or some emulator, which you can trust) for this task?

**Comment by ai** [comment]
> I don't see a good way to do it without hardcoding the colours.

We can set `theme-color` meta tag in JS. In JS we can read manually `document.body` computed colors or try to find some API to get CSS Custom Property value.

**Comment by ai** [comment]
Also, thanks for doing a greet deep research. I like it 🔥

**Comment by privorotskii** [comment]
> OK. Let’s add it only for Chrome for Android (still a big use base). But even Chrome for Android use theme-color not every time but only in light theme (we may still want to support dark theme for the future).

Okay, makes sense, thanks for the clarification

> Do you have Android and Chrome (or some emulator, which you can trust) for this task?

Not as an Android device, but I think I'll be able to use Android Studio emulator for the testing purposes, should be good enough

> We can set theme-color meta tag in JS. In JS we can read manually document.body computed colors or try to find some API to get CSS Custom Property value.

Makes sense too, will look into it, thanks 👀
